services:

  app:
    container_name: ${APP_HOST}
    build: .
    restart: unless-stopped
    environment:
      CHOKIDAR_USEPOLLING: true
      CHOKIDAR_INTERVAL: 1000
    ports:
      - ${APP_PORT}:3004
    volumes:
      - .:/app
     # - node_modules:/app/node_modules
    networks:
      - terraRipple_network
  mongo:
    image: mongo
    container_name: ${DB_HOST}
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:27017
    networks:
      - terraRipple_network
    volumes:
      - mongo_data:/data/db

volumes:
  node_modules:
  mongo_data:


networks:
  terraRipple_network:
    