services:

  app:
    container_name: ${APP_HOST}
    build: ./server
    restart: unless-stopped
    environment:
      CHOKIDAR_USEPOLLING: true
      CHOKIDAR_INTERVAL: 1000
    ports:
      - ${APP_PORT}:3004
    volumes:
      - ./server:/app
      - node_modules:/app/node_modules
    command: npm start
    networks:
      - terraRipple_network
  mongo:
    image: mongo
    container_name: ${DB_HOST}
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:27017
    networks:
      - terraRipple_network
    volumes:
      - mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      
volumes:
  node_modules:
  mongo_data:

networks:
  terraRipple_network: